Minor vim and postgres changes

diff --git a/be-env.symlink/prophet/prophet-sql-dump b/be-env.symlink/prophet/prophet-sql-dump
--- a/be-env.symlink/prophet/prophet-sql-dump
+++ b/be-env.symlink/prophet/prophet-sql-dump
@@ -28,7 +28,7 @@ fi
 # Handle host:dbname pattern (default dbname to prophet if none specified)
 dbhost=${1%:*}
 dbname=${1#*:}
-if [ "$dbname" -eq "$dbhost" ]; then
+if [ "$dbname" = "$dbhost" ]; then
     dbname=prophet
 fi
 #
@@ -56,5 +56,11 @@ fi
 echo "Beginning dump of '$dbname' from '$dbhost'"
 echo "pg_dump -v -F c -U prophet -h $dbhost $dbname > $destinationFile"
 pg_dump -v -F c -U prophet -h $dbhost $dbname > $destinationFile
+status=$?
+if [ $status -eq 0 ];then
+    echo "COMPLETED: Dump of ${dbhost}:${dbname} to ${destinationFile}"
+else
+    echo "FAILED: Dump of ${dbhost}:${dbname} to ${destinationFile}"
+fi
 
-echo "COMPLETED: Dump of ${dbhost}:${dbname} to ${destinationFile}"
+exit $status
